### ISSUE TITLE
.evaluateJS

### ISSUE THREAD

**Issue by juanReTMS** [globulus/swiftui-webview#1]
Can you please give an example of how to use .evaluateJS?

**Comment by gordan-glavas-codecons** [comment]
Just assign `evaluateJS` to your action binding. The only difference is that you get the result in a callback, and not in the state binding:

```swift
webViewAction = .evaluateJS("yourJSCommand()", { result in
            switch result {
            case .success(let value):
                // handle response value
            case .failure(let error):
                // handle error
            }
        })
```

**Comment by juanReTMS** [comment]
Thanks!

I have another question:
I am trying to create a notification app for a webmail service. When I open the webmail server in Safari, I can immediately enter my credentials via TouchID. Using my app, this is only possible in a very awkward way via the release of the keychain and the search for the correct entry. Do you have any idea how I can achieve the same convenience as in Safari? I am grateful for any help.

**Comment by gordan-glavas-codecons** [comment]
I'm sorry, I never encountered such an issue, can't help.
