### ISSUE TITLE
Save Cookies

### ISSUE THREAD

**Issue by elierayalabernal** [globulus/swiftui-webview#10]
Hello, it would be great to be able to give the option to save and read the cookies, I will integrate this Liberia in my application and I will use it to log in to a website and save the cookies to use them in HTTP requests, because said website does not contain an API. Thanks for the contribution 💚

**Comment by gordan-glavas-codecons** [comment]
Hi, I believe cookies are always managed separately from the WebView, via [WKWebSiteDataStore](https://developer.apple.com/documentation/webkit/wkwebsitedatastore?changes=latest_minor).

**Comment by elierayalabernal** [comment]
Oh Thanks.
