### ISSUE TITLE
Missing canGoBack state update

### ISSUE THREAD

**Issue by psco** [globulus/swiftui-webview#2]
It appears that the _canGoBack_ state is not always updated when it changes. This can result e.g. in a go-back-button not being shown even though go-back would be possible. As a fix I suggest to extend the state update logic in
`public func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!)`
to cover an update to _canGoBack_ besides the update to _isLoading_. Probably _canGoForward_ should be handled similarly.

**Comment by gordan-glavas-codecons** [comment]
Hi! I'm aware of this, but it seems to boil down to buggy behaviour in WKWebView. Even if I put extra updates in webView(_:didFinish:), I can still get into a state where back is unavailable when it should be, or when forward is temporarily shown when it doesn't make sense. Have you tried this approach yourself and found it to be more consistent (even if not perfect)?

**Comment by psco** [comment]
I've added a state update for _canGoBack_ and _canGoForward_ in _webView(_:didFinish:)_ and haven't seen a missed go-back resp. go-forward since then. Actually it would be quite surprising if webView(_:didFinish:) would not be called consistently (this would indeed be a bug in WKWebView).

**Comment by gordan-glavas-codecons** [comment]
Changes made in v.1.0.5.
