### ISSUE TITLE
'mediaPlaybackRequiresUserAction' was deprecated in iOS 9.0

### ISSUE THREAD

**Issue by fletch29** [globulus/swiftui-webview#3]
I consistently get a warning from Xcode Version 13.2.1 (13C100) when compiling a project against SwiftUIWebView 1.0.3:
```
swiftui-webview/Sources/SwiftUIWebView/SwiftUIWebView.swift:214:23: 'mediaPlaybackRequiresUserAction' was deprecated in iOS 9.0
```

**Comment by fletch29** [comment]
`mediaPlaybackRequiresUserAction` deprecated in favor of `mediaTypesRequiringUserActionForPlayback`.
PR incoming

**Comment by gordan-glavas-codecons** [comment]
Resolved with PR.
