### ISSUE TITLE
Potential multiple executions of go back and go forward

### ISSUE THREAD

**Issue by psco** [globulus/swiftui-webview#5]
When setting .action to .goBack resp. .goForward it is possible that the corresponding go-back resp. go-forward action is executed more than once. This behavior is already exhibited by the small browser app. I believe this is due to
`        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
            action = .idle
        }
`
which leaves a window open for multiple executions. Unfortunately the simple
`action = .idle`
leads to warnings claiming undefined behavior.

**Comment by gordan-glavas-codecons** [comment]
Hi, I'm not aware of a better way to set this since the view is produced via a `UIViewRepresentable`. There's an experimental setup that uses `PreferenceKey` to propagate the action setting back to `idle` safely, but it doesn't work as expected (you can see it in preference-key-testing branch of this project).

**Comment by psco** [comment]
I have added a boolean guard to _WebViewCoordinator_

`
public class WebViewCoordinator: NSObject {
    private let webView: WebView
    var ignoreAction = false
...
`

modified _updateUIView_ 

`        if action == .idle || context.coordinator.ignoreAction {
            return
        }
        context.coordinator.ignoreAction = true
...
`

and moved all the _.action = .idle_ updates to the appropriate _WKNavigationDelegate_ functions, e.g.

`
    public func webViewWebContentProcessDidTerminate(_ webView: WKWebView) {
        setLoading(false)
        self.webView.action = .idle
        ignoreAction = false
    }
`

(similarly for didFinish and didFail)
This works for me - go-back resp. go-forward is executed exactly once.

**Comment by gordan-glavas-codecons** [comment]
I just tested this briefly and it seems to work. Would you like to make a PR and be a contributor or should I commit the changes after I test them some more (the same goes for the other issue you opened)?

**Comment by psco** [comment]
Please go ahead and commit the changes yourself. I've already done quite a few modifications to remove features I do not need which would make a PR from my side a bit risky.

**Comment by gordan-glavas-codecons** [comment]
Changes made in v.1.0.5. Thanks for everything!
