### ISSUE TITLE
Possibly missing setLoading(false)

### ISSUE THREAD

**Issue by psco** [globulus/swiftui-webview#6]
I think there should also be a _setLoading(false)_ after _decisionHandler(.cancel)_. I'm quite sure for the second occurrence (i.e. where the scheme handler is invoked) but cannot really tell for the first case as I have removed this feature for my case.

I noticed this with a scheme handler for _itms-apps_ which just invokes the app store: When returning from the app store the loading wheel was still spinning.

**Comment by gordan-glavas-codecons** [comment]
You're right, I added the change in v.1.0.5.
