### ISSUE TITLE
Links with target="_blank" not loading

### ISSUE THREAD

**Issue by WingedToaster** [globulus/swiftui-webview#9]
Hello,

When clicking on a link with the `target="_blank"` attribute nothing happens.

Appears some special logic needs to be added to a delegate method to allow this to work.
https://stackoverflow.com/questions/66700248/how-to-open-urls-with-target-blank-in-safari-wkwebview-webkit

**Comment by globulus** [comment]
The issue is fixed in v.1.0.8. Thanks for reporting!
